version: '3.8' 

services:
  postgres:
    image: postgres:latest
    container_name: users-db
    environment:
      POSTGRES_USER: postgres      
      POSTGRES_PASSWORD: yourpassword     
      POSTGRES_DB: users-db         
    ports:
      - "5432:5432"                        
    volumes:
      - postgres_data:/var/lib/postgresql/data  

volumes:
  postgres_data:
