version: '3.8' 

services:
  postgres:
    image: postgres:latest
    container_name: users-db
    environment:
      POSTGRES_USER: postgres      
      POSTGRES_PASSWORD: yourpassword     
      POSTGRES_DB: users-db         
    ports:
      - "5432:5432"                        
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network  

  oracle:
    image: gvenzl/oracle-xe
    container_name: products-db
    environment:
      ORACLE_PASSWORD: yourpassword
      ORACLE_ALLOW_REMOTE: "true"
    ports:
      - "1521:1521"
    volumes:
      - oracle_data:/opt/oracle/oradata 
    networks:
      - app-network    

volumes:
  postgres_data:
  oracle_data:  

networks:
  app-network:
    driver: bridge    
