services:
  postgres:
    image: postgres:latest
    container_name: users-db
    environment:
      POSTGRES_USER: postgres      
      POSTGRES_PASSWORD: yourpassword     
      POSTGRES_DB: users-db         
    ports:
      - "5432:5432"                        
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network  

  oracle:
    image: gvenzl/oracle-xe
    container_name: products-db
    environment:
      ORACLE_PASSWORD: yourpassword
      ORACLE_ALLOW_REMOTE: "true"
    ports:
      - "1521:1521"
    volumes:
      - oracle_data:/opt/oracle/oradata 
    networks:
      - app-network
      
  zookeeper:
    image: 'bitnami/zookeeper:latest'
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    ports:
      - '2181:2181'
    networks:
      - app-network    

  kafka:
    image: 'bitnami/kafka:latest'
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_LISTENERS=PLAINTEXT://0.0.0.0:9092 
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://localhost:9092
      - ALLOW_PLAINTEXT_LISTENER=yes
    ports:
      - '9092:9092'
    depends_on:
      - zookeeper
    networks:
      - app-network    

volumes:
  postgres_data:
  oracle_data:  

networks:
  app-network:
    driver: bridge    
