spring:
  application:
    name: user-manager
  datasource:
    url: jdbc:postgresql://${RDS_HOSTNAME:localhost}:${RDS_PORT:1234}/${RDS_DB_NAME:users-db}
    username: ${RDS_USERNAME:postgres}
    password: ${RDS_PASSWORD:yourpassword}
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  kafka:
    bootstrap-servers: >
      b-1.eshop.jvk64j.c2.kafka.eu-north-1.amazonaws.com:9092,
      b-2.eshop.jvk64j.c2.kafka.eu-north-1.amazonaws.com:9092,
      b-3.eshop.jvk64j.c2.kafka.eu-north-1.amazonaws.com:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
    consumer:
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer

server:
  port: 8080