spring:
  application:
    name: product-manager
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB
  datasource:
    url: jdbc:postgresql://${RDS_HOSTNAME:localhost}:${RDS_PORT:1234}/${RDS_DB_NAME:products-db}
    username: ${RDS_USERNAME:postgres}
    password: ${RDS_PASSWORD:yourpassword}
  jpa:
    hibernate:
      ddl-auto: update
  kafka:
    bootstrap-servers: >
      b-1.eshop.jvk64j.c2.kafka.eu-north-1.amazonaws.com:9092,
      b-2.eshop.jvk64j.c2.kafka.eu-north-1.amazonaws.com:9092,
      b-3.eshop.jvk64j.c2.kafka.eu-north-1.amazonaws.com:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
    consumer:
      group-id: product-group
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer

client:
  user-manager:
    base-url: http://gccc.eu-north-1.elasticbeanstalk.com:8080/

server:
  port: 8081